<?php

namespace Tests\Unit;

use App\Services\FcmSenderService;
use Tests\TestCase;

class FcmTest extends TestCase
{
    /**
     * @var FcmSenderService
     */
    private  $fcmService;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->fcmService = new FcmSenderService();
    }

    /**
     * vendor/bin/phpunit --filter testSubcribleTopic tests/Unit/FcmTest.php
     *
     * @return void
     */
    public function testSubcribleTopic()
    {
        $topicName = FcmSenderService::getTopicByInvestorId("1234567-a");
        $this->fcmService->registerTopic("abcde-123", $topicName);

        $this->assertTrue(true);
    }
}
